/* GENERATED by tools/lang/train_classifier.js — do not hand-edit.
 * Rollback = repoint this file at a previously committed
 * classifier.v1.<sha8>.ts (CLAUDE.md: "Never overwrite a published
 * weight artifact. Rollback = repoint manifest."). classify.ts imports
 * this file, and only this file, by name. */
export { WEIGHTS } from "./classifier.v1.7a3096b7.js";
export const CURRENT = "classifier.v1.7a3096b7";
